### ISSUE TITLE
GPIO Expander Driver

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/Cerberus#8]
This driver corresponds to the GPIO expander that monitors a lot of things on the PDU. This driver is gonna be a bit weird in that we probably want to be able to easily read each channel (ADC, toggle, etc) but then we also need to classify them on a higher level (i.e. turn motor on, read energy meter) so I'm not sure if that should happen on a driver level or monitoring level

**Comment by nwdepatie** [comment]
Part number for this GPIO expander is PI4IOE5V9535ZDEX, probably should name stuff ```pi4ioe```

**Comment by dyldonahue** [comment]
@nwdepatie im gonna create two layers, one that directly reads/writes and another that utlizes those to do specifc things like "turn motor on", read enery meter etc. If u or @HamzaIqbal69 wanna move the second layer to application later on feel free to, ill make it so that itll be portable but migth as well jsut do both here for n ow
